= Print This

Generate a book with Asciidoctor.

Typesetting for print-on-demand printing is complex!
Use this as a starting point for your own print book.

== Usage

[source,bash]
----
cd book
./build.sh
----

== Issues

Here's a brief summary of the stuff we are aware of and working on.

|===
|ID |Description |Status |Resolution Details

|ad01 |add usage info |RESOLVED |
|ad02 |translate to any language besides English |OPEN |
|ad03 |support Lulu |OPEN |
|ad04 |support another printer/publisher besides Lulu |OPEN |
|ad05 |document all attributes at top of `print-this.adoc` |OPEN |
|===

We maintain our own issue list here so this repository is more useful on its own.
IDs start with `ad` to avoid conflicts with IDs that might be generated by some other issue tracker, should we choose one.
Completed items can be removed, just make sure to leave the last one so we don't skip IDs.
Please leave cell widths as-is, optimizing for proper diffs in source control history.

== Conventions

* pay attention to and follow the existing style
** standardize whenever possible and formalize conventions here
* source control
** commit early and often
** group logically related changes into single commits
*** consider future maintainers may wish to `git revert`: try to make that easy for them
** group a series of related changes in a branch
** squashing is OK
** before submitting patches:
*** ensure build passes
** commit log messages
*** the first line of a commit log message is very important: say precisely *what* change you made, save the *why* for the rest
*** use infinitive verb forms, e.g. "add -q quiet option"
*** don't wrap body text
*** see also:
**** https://mifosforge.jira.com/wiki/spaces/MIFOS/pages/4456742/Commit+Log+Guide
**** https://lore.kernel.org/git/7vr4waoics.fsf@alter.siamese.dyndns.org/
**** https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

== Warranty

None.

== Copyright and license

(C)2023 Adam Monsen and all Print This authors mentioned in source control history.

The license for all original source code related to this book is the GNU AGPL (Affero General Public License) as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

The license for the book content itself (what little there is) is Creative Commons CC0 1.0 Universal.
